sudo: required
dist: trusty
language: c
before_install:
  - sudo apt-get -y install texlive-luatex texlive-lang-cjk lmodern texlive-xetex make pandoc golang
  - go get github.com/tcnksm/ghr
script:
  - make
  - if [ -n "$TRAVIS_TAG" ] && [ $TRAVIS_TAG != "latest" ]; then $GOPATH/bin/ghr -u kmc-jp --replace $TRAVIS_TAG release; fi
  - if [ $TRAVIS_BRANCH = "master" ]; then git tag -f latest; $GOPATH/bin/ghr -u kmc-jp --replace latest release; fi
env:
  global:
    - GOPATH=~/.go
    - secure: FwZn9HHmmCbq1E/KkAYxe1XPIEyLh5yhC0OLKQU+0H4GMg67RlRvnjlkpZQyXAr09xnj6MhWujEO+/BtUiIrC+ijgHrKAESoXWX3n14HBtJfRyPYY3ojTWyUEpkSd9wnKt18/UBhzslX09/uDBtIxgYn+aVMaXtY97TBGmFh4Kdbovy84UjSw3LDPMaXwxrKeh4ul014eS1Fi2x5G9EtWflbDBFpJOS98K6VWCPXjys7hcqBo8LpzDzd2IRlZowWVU4Ee8CidA3ryowS+C2J9xDKMi7+eZn8rDPX5lNaVtmHkS3p8sBli+Dn3TWn7mac9ghzsd70Y2r7SFeJCMeCMBpoBXiJFdijKFo9+USOZ0vKjfIr+rU8yrAcr+8yHu/HcTUtBm9v++2+QiSkGaX3d8Z934pxVh4AGceLEneW69rIF9hL3fJUsKjMYlHINZix2UnnzAWwaQAuawtY0002dkirTbYhZ42sRJOSeiITO++Kl3748Ywu1vGM7o6I1H7SL/Y3oeJPvdEbjJNEhV3TXdDHUW9qdx+da5CxO/YVG5ca+SJIoM3uGtK1V2iVWSrz8s1CvmyFWIkQv5M6RfhWJhGMs5UuhcHk88tTfRSgQaf+QYPKXnaJtx5EF82DcvE0K6/TzfrTsKg1/I/vh1i7FqROQNjjg2Z/e7YSir4bUKw=
